/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_smile_mygeeknews_ui_main_WelcomeActivity */

#ifndef _Included_com_smile_mygeeknews_ui_main_WelcomeActivity
#define _Included_com_smile_mygeeknews_ui_main_WelcomeActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_smile_mygeeknews_ui_main_WelcomeActivity
 * Method:    calculate
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_smile_mygeeknews_ui_main_WelcomeActivity_calculate
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
